name: Deploy Docs

on:
  push:
    branches: [main]
    paths: ['docs/**']
  # schedule:
  #   - cron: '0 0 */2 * *'  # Runs every 2 days at 00:00 UTC
  #     timezone: 'Asia/Shanghai'
  #  - cron: '0 23 * * *'   # 7am SGT (UTC+8) = 11pm UTC previous day
  workflow_dispatch:      # Allow manual trigger
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
          publish_branch: gh-pages
          enable_jekyll: true
